Repository DEFRA/flood-risk-back-office, pull requests merged in 2019-06, with the labels that each got.

#96 Remove circle-ci from repo
  README.md
  circle.yml
Labels: housekeeping

#97 Remove overcommit from repo
  .htmlhintrc
  .overcommit.yml
  README.md
Labels: housekeeping

#95 Update dependencies
  Gemfile
  Gemfile.lock
  spec/controllers/admin/enrollment_exemptions/approve_controller_spec.rb
  spec/controllers/admin/enrollment_exemptions/change_status_controller_spec.rb
  spec/controllers/admin/enrollment_exemptions/deregister_controller_spec.rb
  spec/controllers/admin/enrollment_exemptions/reject_controller_spec.rb
  spec/controllers/admin/enrollment_exemptions/resend_approval_email_controller_spec.rb
  spec/controllers/admin/enrollment_exemptions/withdraw_controller_spec.rb
  spec/controllers/admin/enrollments_controller_spec.rb
  spec/controllers/enrollments/addresses_controller_spec.rb
  spec/controllers/enrollments/partners_controller_spec.rb
  spec/factories/approved_enrollments_factory.rb
  spec/factories/enrollment_export_factory.rb
  spec/factories/enrollments_factory.rb
  spec/factories/rejected_enrollments_factory.rb
  spec/factories/submitted_enrollments_factory.rb
  spec/factories/user_factory.rb
  spec/features/admin/view_enrollment_exemption_spec.rb
  spec/features/nav_menu_feature_spec.rb
  spec/forms/admin/enrollment_exemptions/approve_form_spec.rb
  spec/forms/admin/enrollment_exemptions/assistance_form_spec.rb
  spec/forms/admin/enrollment_exemptions/change_status_form_spec.rb
  spec/forms/admin/enrollment_exemptions/deregister_form_spec.rb
  spec/forms/admin/enrollment_exemptions/in_progress_form_spec.rb
  spec/forms/admin/enrollment_exemptions/reject_form_spec.rb
  spec/forms/admin/enrollment_exemptions/resend_approval_email_form_spec.rb
  spec/forms/admin/enrollment_exemptions/withdraw_form_spec.rb
  spec/forms/admin/enrollment_form_spec.rb
  spec/forms/enrollments/address_form_spec.rb
  spec/forms/enrollments/partner_form_spec.rb
  spec/models/enrollment_export_spec.rb
  spec/models/flood_risk_engine/enrollment_exemption_spec.rb
  spec/rails_helper.rb
  spec/services/send_registration_approved_email_spec.rb
  spec/services/send_registration_rejected_email_spec.rb
  spec/support/factory_bot.rb
  spec/support/factory_girl.rb
Labels: housekeeping

#98 Remove heroku from repo
  Gemfile
  Gemfile.lock
  Procfile
  README.md
Labels: housekeeping

#99 Integrate CI tools with repo
  .travis.yml
  README.md
  config/database.travis.yml
Labels: housekeeping

#118 Inherit engine styles
  app/assets/stylesheets/application.css.scss
Labels: feature

#123 Add github changelog generator to the project
  CHANGELOG.md
  Gemfile
  Gemfile.lock
  lib/tasks/changelog.rake
Labels: housekeeping

#124 Move github changelog generator to main group
  Gemfile
Labels: bug
