Repository DEFRA/flood-risk-back-office, pull requests merged in 2020-01, with the labels that each got.

#190 Add Close Airbrake lib
  lib/close_airbrake.rb
Labels: enhancement

#189 Add defra_ruby_aws gem and configs for EPR export
  .env.example
  .travis.yml
  Gemfile
  Gemfile.lock
  config/initializers/defra_ruby_aws.rb
Labels: enhancement

#193 Add epr rake task and service
  .rubocop.yml
  app/services/concerns/can_load_file_to_aws.rb
  app/services/reports/epr_export_service.rb
  config/application.rb
  lib/tasks/reports.rake
  spec/.env.example
  spec/services/reports/epr_export_service_spec.rb
Labels: enhancement

#196 Schedule EPR export
  config/schedule.rb
Labels: enhancement

#195 Add EPR export serializer and persenter
  app/models/reports/epr_serializer.rb
  app/presenters/reports/epr_presenter.rb
  app/services/reports/epr_export_service.rb
  config/locales/en.yml
  config/locales/time_formats.yml
  spec/models/reports/epr_serializer_spec.rb
  spec/presenters/reports/epr_presenter_spec.rb
  spec/services/reports/epr_export_service_spec.rb
Labels: enhancement

#197 Add format year_month_day_hyphens for time objects
  config/locales/time_formats.yml
Labels: bug

#198 Remove close airbrake lib
  lib/close_airbrake.rb
  lib/tasks/reports.rake
Labels: bug

#199 Fix changelog generator
  lib/tasks/changelog.rake
Labels: housekeeping
