Repository DEFRA/flood-risk-back-office, pull requests merged in 2021-09, with the labels that each got.

#314 Styling: Devise pages
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/shared/_back.html.erb
  app/views/shared/_validation_errors.html.erb
  config/locales/en.yml
  spec/features/devise/forgotten_password_feature_spec.rb
Labels: enhancement

#316 Add hidden labels to the Search and Select menus
  app/views/admin/enrollment_exemptions/index.html.erb
  config/locales/admin/enrollment_exemptions/index/enrollment_exemptions.en.yml
Labels: enhancement

#317 Styling: View Registration - Enhancements
  app/views/admin/enrollment_exemptions/show/_comment_history.html.erb
  app/views/admin/enrollment_exemptions/show/_main.html.erb
Labels: enhancement

#318 Add an ID attribute to match the aria-labelled by
  app/views/shared/_flash_alerts.html.erb
Labels: enhancement

#319 Update engine to use new reg workflow
  Gemfile.lock
  app/forms/enrollments/address_form.rb
  db/schema.rb
Labels: enhancement

#315 Styling: New Registration
  app/views/layouts/flood_risk_engine.html.erb
  config/initializers/assets.rb
  spec/features/admin/new_registration_spec.rb
Labels: enhancement

#321 Styling: View users - Enhancements
  app/views/admin/users/index.html.erb
  app/views/layouts/_navbar.html.erb
  config/locales/users.en.yml
  spec/features/nav_menu_feature_spec.rb
Labels: enhancement

#324 Update flood_risk_engine
  Gemfile.lock
Labels: dependencies

#325 Styling: Edit registration
  app/controllers/admin/enrollments_controller.rb
  app/controllers/enrollments/correspondence_contacts_controller.rb
  app/controllers/enrollments/organisations_controller.rb
  app/controllers/enrollments/secondary_contacts_controller.rb
  app/forms/admin/enrollment_form.rb
  app/models/correspondence_contact.rb
  app/models/organisation.rb
  app/models/secondary_contact.rb
  app/policies/correspondence_contact_policy.rb
  app/policies/organisation_policy.rb
  app/policies/secondary_contact_policy.rb
  app/presenters/enrollment_exemption_presenter.rb
  app/views/admin/enrollment_exemptions/show/_actions.html.erb
  app/views/admin/enrollment_exemptions/show/_correspondant.html.erb
  app/views/enrollments/correspondence_contacts/edit.html.erb
  app/views/enrollments/organisations/edit.html.erb
  app/views/enrollments/secondary_contacts/edit.html.erb
  config/locales/admin/enrollment_exemptions/show.en.yml
  config/locales/admin/enrollment_exemptions/show/correspondant.en.yml
  config/locales/admin/enrollments.en.yml
  config/locales/admin/enrollments/edit.yml
  config/locales/en.yml
  config/locales/enrollments/correspondence_contacts.en.yml
  config/locales/enrollments/organisations.en.yml
  config/locales/enrollments/secondary_contacts.en.yml
  config/routes.rb
  spec/controllers/admin/enrollments_controller_spec.rb
  spec/features/admin/new_enrollment_spec.rb
  spec/features/admin/view_enrollment_exemption_spec.rb
  spec/features/edit_correspondence_contact_spec.rb
  spec/features/edit_organisation_spec.rb
  spec/features/edit_secondary_contact_spec.rb
  spec/forms/admin/enrollment_form_spec.rb
  spec/models/correspondence_contact_spec.rb
  spec/models/organisation_spec.rb
Labels: enhancement

#326 Validate the postcode format
  app/models/address.rb
  config/locales/activemodel.yml
  spec/features/edit_address_spec.rb
Labels: enhancement

#329 Validate the postcode length
  app/models/address.rb
  config/locales/en.yml
  spec/features/edit_address_spec.rb
  spec/models/address_spec.rb
Labels: enhancement

#335 Update engine
  Gemfile.lock
  app/controllers/application_controller.rb
  app/views/invitations/edit.html.erb
  app/views/invitations/new.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/flood_risk_engine.html.erb
  spec/features/new_registration_spec.rb
Labels: dependencies

#333 Styling: Exports
  app/controllers/admin/enrollment_exports_controller.rb
  app/forms/admin/base_form.rb
  app/forms/admin/enrollment/export_form.rb
  app/models/enrollment_export.rb
  app/views/admin/enrollment_exports/_enrollment_export.html.erb
  app/views/admin/enrollment_exports/_form.html.erb
  app/views/admin/enrollment_exports/index.html.erb
  config/locales/activemodel.yml
  config/locales/admin/enrollment_exports.en.yml
  config/locales/en.yml
  spec/features/export_spec.rb
  spec/forms/admin/enrollment/export_form_spec.rb
  spec/models/enrollment_export_spec.rb
Labels: enhancement

#338 Update engine
  Gemfile.lock
Labels: dependencies

#337 Cleanup old code
  Gemfile
  Gemfile.lock
  app/controllers/admin/enrollment_exemptions_controller.rb
  app/forms/search_form.rb
  app/helpers/application_helper.rb
  app/policies/flood_risk_engine/enrollment_exemption_policy.rb
  config/initializers/reform.rb
  spec/controllers/admin/enrollments_controller_spec.rb
  spec/features/admin/disable_enable_user_feature_spec.rb
  spec/features/admin/edit_user_role_feature_spec.rb
  spec/support/matchers/have_form_error.rb
Labels: housekeeping

#339 Update engine
  Gemfile.lock
Labels: dependencies

#340 Improve UX for list of back office users
  app/controllers/admin/users_controller.rb
  app/policies/user_policy.rb
  app/views/admin/users/index.html.erb
  config/locales/users.en.yml
  config/routes.rb
  spec/features/admin/list_users_feature_spec.rb
Labels: enhancement

#342 Validate the length of the comment's content
  app/models/enrollment_exemption.rb
  config/locales/en.yml
  spec/models/enrollment_exemption_spec.rb
Labels: enhancement

#343 Prepend user email to comments
  app/controllers/admin/enrollment_exemptions/approve_controller.rb
  app/controllers/admin/enrollment_exemptions/change_status_controller.rb
  app/controllers/admin/enrollment_exemptions/deregister_controller.rb
  app/controllers/admin/enrollment_exemptions/in_progress_controller.rb
  app/controllers/admin/enrollment_exemptions/reject_controller.rb
  app/controllers/admin/enrollment_exemptions/resend_approval_email_controller.rb
  app/controllers/admin/enrollment_exemptions/withdraw_controller.rb
  app/models/enrollment_exemption.rb
  app/views/admin/enrollment_exemptions/show/_comment_history.html.erb
  spec/features/approve_spec.rb
  spec/features/change_status_spec.rb
  spec/features/deregister_spec.rb
  spec/features/in_progress_spec.rb
  spec/features/reject_spec.rb
  spec/features/resend_approval_email_spec.rb
  spec/features/withdraw_spec.rb
  spec/models/enrollment_exemption_spec.rb
Labels: enhancement

#344 Fix the html page <title>
  app/views/admin/enrollment_exemptions/approve/new.html.erb
  app/views/admin/enrollment_exemptions/change_status/new.html.erb
  app/views/admin/enrollment_exemptions/deregister/new.html.erb
  app/views/admin/enrollment_exemptions/in_progress/new.html.erb
  app/views/admin/enrollment_exemptions/index.html.erb
  app/views/admin/enrollment_exemptions/reject/new.html.erb
  app/views/admin/enrollment_exemptions/resend_approval_email/new.html.erb
  app/views/admin/enrollment_exemptions/show.html.erb
  app/views/admin/enrollment_exemptions/withdraw/new.html.erb
  app/views/admin/enrollment_exports/index.html.erb
  app/views/admin/users/edit.html.erb
  app/views/admin/users/edit_disable.html.erb
  app/views/admin/users/index.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/invitations/edit.html.erb
  app/views/invitations/new.html.erb
Labels: enhancement

#345 Add warning text to Resend email page
  app/views/admin/enrollment_exemptions/resend_approval_email/new.html.erb
Labels: enhancement

#346 Edit user: text changes
  app/views/admin/users/_role_help.html.erb
  config/locales/user_roles.en.yml
Labels: enhancement

#347 Add a title to the generic validation error page to fix aria issue
  app/views/shared/_validation_errors.html.erb
  config/locales/en.yml
Labels: enhancement

#348 Change 'In Progress' to 'In progress'
  config/locales/admin/enrollment_exemptions/in_progress.yml
  config/locales/admin/enrollment_exemptions/show.en.yml
  spec/features/in_progress_spec.rb
Labels: enhancement

#351 Prefer <h2> for subheading
  app/views/admin/users/_role_help.html.erb
Labels: enhancement

#354 Sign out via :get instead of :delete
  app/views/layouts/_navbar.html.erb
  config/initializers/devise.rb
Labels: bug

#355 Avoid assigning an invited user multiple roles
  app/controllers/invitations_controller.rb
  spec/features/devise/invite_user_feature_spec.rb
Labels: enhancement

#353 Add a Content Security Policy
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.css.scss
  app/views/admin/enrollment_exemptions/index.html.erb
  config/initializers/secure_headers.rb
Labels: enhancement

#352 Upgrade to Rails 6.1
  Gemfile
  Gemfile.lock
  app/mailers/registration_approved_mailer.rb
  app/mailers/registration_rejected_mailer.rb
  app/presenters/exemption_email_presenter.rb
  config/environments/development.rb
  config/environments/test.rb
Labels: dependencies

#356 Update engine and configure default assistance mode
  Gemfile.lock
  config/initializers/flood_risk_engine.rb
Labels: enhancement

#361 Bump the engine
  Gemfile.lock
Labels: dependencies
